language: node_js

services:
  - xvfb

branches:
  only:
  - master
  - /^release\/.*$/

stages:
  - check
  - test
  - release-rc-npm
  - release-rc-docker
  - test-external

node_js:
  - 'lts/*'
  # cannot support node 14 until hapi > 19.1.1 is released
  # - 'node'

os:
  - linux
  - osx
  - windows

env:
  # This stops Windows builds from hanging
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

addons:
  apt:
    packages:
      # Fixes error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
      # https://github.com/electron/electron/issues/1518
      - libgconf-2-4
      # Ensure chrome is the latest version
      # https://stackoverflow.com/questions/57903415/travis-ci-chrome-62-instead-of-77
      - dpkg
  chrome: stable

before_install:
  # prevents windows error: npm ERR! ... git-sh-setup: file not found
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH=/c/PROGRA~1/Git/usr/bin:/c/PROGRA~1/Git/mingw64/libexec/git-core:$PATH ; fi
  # only run jobs in packages that have changed since master in PR builds
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export RUN_SINCE='--since master' ; fi

script: npm run test:node -- $RUN_SINCE -- -- --timeout 10000 --bail

jobs:
  include:
    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - npm run test:browser -- $RUN_SINCE -- -- --bail

notifications:
  email: false
